/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResellersRouteImport } from './routes/_authenticated/resellers'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedArchivesRouteImport } from './routes/_authenticated/archives'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts.index'
import { Route as AuthenticatedContactsNewRouteImport } from './routes/_authenticated/contacts.new'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/_authenticated/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResellersRoute = AuthenticatedResellersRouteImport.update({
  id: '/_authenticated/resellers',
  path: '/resellers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/_authenticated/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/_authenticated/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArchivesRoute = AuthenticatedArchivesRouteImport.update({
  id: '/_authenticated/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/_authenticated/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/_authenticated/contacts/',
    path: '/contacts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContactsNewRoute =
  AuthenticatedContactsNewRouteImport.update({
    id: '/_authenticated/contacts/new',
    path: '/contacts/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/_authenticated/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/archives': typeof AuthenticatedArchivesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/resellers': typeof AuthenticatedResellersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/archives': typeof AuthenticatedArchivesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/resellers': typeof AuthenticatedResellersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/archives': typeof AuthenticatedArchivesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/resellers': typeof AuthenticatedResellersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/contacts/new': typeof AuthenticatedContactsNewRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/archives'
    | '/dashboard'
    | '/kanban'
    | '/onboarding'
    | '/resellers'
    | '/settings'
    | '/tasks'
    | '/contacts/$id'
    | '/contacts/new'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/archives'
    | '/dashboard'
    | '/kanban'
    | '/onboarding'
    | '/resellers'
    | '/settings'
    | '/tasks'
    | '/contacts/$id'
    | '/contacts/new'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/analytics'
    | '/_authenticated/archives'
    | '/_authenticated/dashboard'
    | '/_authenticated/kanban'
    | '/_authenticated/onboarding'
    | '/_authenticated/resellers'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/contacts/new'
    | '/_authenticated/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedArchivesRoute: typeof AuthenticatedArchivesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedResellersRoute: typeof AuthenticatedResellersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedContactsNewRoute: typeof AuthenticatedContactsNewRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resellers': {
      id: '/_authenticated/resellers'
      path: '/resellers'
      fullPath: '/resellers'
      preLoaderRoute: typeof AuthenticatedResellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/archives': {
      id: '/_authenticated/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof AuthenticatedArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts/new': {
      id: '/_authenticated/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthenticatedContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedArchivesRoute: AuthenticatedArchivesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedResellersRoute: AuthenticatedResellersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedContactsNewRoute: AuthenticatedContactsNewRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
